# Generated by Django 5.2.3 on 2026-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('engagement_started', 'Engagement Started'), ('engagement_completed', 'Engagement Completed'), ('milestone', 'Milestone')], max_length=50),
        ),
    ]
