# Generated by Django 5.2.3 on 2026-01-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_num', models.CharField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')])),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=60)),
                ('level', models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (700, '700')])),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('skills', models.JSONField(default=list)),
                ('expected_grad_year', models.CharField(max_length=4)),
                ('preferred_industry', models.CharField(blank=True, null=True)),
                ('preferred_company_type', models.CharField(blank=True, null=True)),
                ('willingness_to_be_mentored', models.BooleanField(default=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('x_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
