# Generated by Django 5.2.3 on 2026-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20),
        ),
    ]
