# Generated by Django 5.2.3 on 2026-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
