# Generated by Django 5.2.3 on 2026-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alumniprofile_avg_rating_alumniprofile_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
