# Generated by Django 5.2.3 on 2026-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pg_trgm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumniprofile",
            name="matric_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="alumniprofile",
            name="faculty",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="matric_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
