# Generated by Django 5.2.3 on 2026-05-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='internshipengagement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='internshipoffer',
            unique_together=set(),
        ),
    ]
