# Generated by Django 5.2.3 on 2026-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_internshipapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.CharField(default='Company 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='company_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_type',
            field=models.CharField(default='Tech'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='company_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='levels',
            field=models.JSONField(default=list),
        ),
    ]
