# Generated by Django 5.2.3 on 2026-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_internshipengagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
