# Generated by Django 5.2.3 on 2026-08-12 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='duration_weeks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
