# Generated by Django 5.2.3 on 2026-01-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_num', models.CharField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')])),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=20)),
                ('grad_year', models.CharField(max_length=4)),
                ('current_job_title', models.CharField()),
                ('current_company', models.CharField()),
                ('industry', models.CharField()),
                ('years_of_exp', models.IntegerField()),
                ('previous_comps', models.JSONField(blank=True, default=list, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('company_website_url', models.URLField(blank=True, null=True)),
                ('x_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
