# Generated by Django 5.2.3 on 2026-05-22 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('internship_created', 'Internship created'), ('mentorship_created', 'Mentorship created'), ('event_created', 'Event created')], max_length=50)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('student', 'Student'), ('alumni', 'Alumni')], default='public', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='feed_feedev_created_986eb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='feed.feedevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event'], name='feed_feedim_user_id_b6be25_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='FeedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('skill', 'Skill'), ('department', 'Department'), ('level', 'Level'), ('faculty', 'Faculty'), ('industry', 'Industry'), ('company_type', 'Company Type')], max_length=50)),
                ('target_value', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='feed.feedevent')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_value'], name='feed_feedta_target__b94292_idx')],
                'unique_together': {('event', 'target_type', 'target_value')},
            },
        ),
    ]
