# Generated by Django 5.2.3 on 2026-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='event_type',
            field=models.CharField(choices=[('internship_created', 'Internship created'), ('mentorship_created', 'Mentorship created'), ('event_created', 'Event created'), ('internship_started', 'Internship started'), ('mentorship_started', 'Mentorship started')], max_length=50),
        ),
    ]
