# Generated by Django 5.2.3 on 2026-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feedevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtarget',
            name='target_type',
            field=models.CharField(choices=[('skill', 'Skill'), ('department', 'Department'), ('level', 'Level'), ('faculty', 'Faculty'), ('industry', 'Industry'), ('company_type', 'Company Type'), ('category', 'Category')], max_length=50),
        ),
    ]
