# Generated by Django 5.2.3 on 2026-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feedtarget_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedevent',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedevent',
            name='event_type',
            field=models.CharField(choices=[('internship_created', 'Internship created'), ('mentorship_created', 'Mentorship created'), ('event_created', 'Event created'), ('internship_started', 'Internship started'), ('mentorship_started', 'Mentorship started'), ('internship_completed', 'Internship completed'), ('mentorship_completed', 'Mentorship completed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['-score', '-created_at'], name='feed_feedev_score_672c5d_idx'),
        ),
    ]
