# Generated by Django 5.2.3 on 2026-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feedevent_score_alter_feedevent_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedevent',
            name='feed_feedev_score_672c5d_idx',
        ),
        migrations.AddField(
            model_name='feedevent',
            name='shuffle_seed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['-score', 'shuffle_seed'], name='feed_feedev_score_6baef7_idx'),
        ),
    ]
