# Generated by Django 5.2.3 on 2026-05-28 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('career_guidance', 'Career Guidance'), ('cv_and_portfolio', 'CV & Portfolio Building'), ('interview_prep', 'Interview Preparation'), ('linkedin_branding', 'LinkedIn & Personal Branding'), ('salary_negotiation', 'Salary Negotiation'), ('software_engineering', 'Software Engineering'), ('data_science', 'Data Science & Analytics'), ('product_management', 'Product Management'), ('product_design', 'Product Design & UX'), ('cybersecurity', 'Cybersecurity'), ('cloud_devops', 'Cloud & DevOps'), ('embedded_systems', 'Embedded Systems & IoT'), ('research_academia', 'Research & Academia'), ('entrepreneurship', 'Entrepreneurship'), ('freelancing', 'Freelancing & Remote Work'), ('fintech', 'Fintech'), ('agritech', 'Agritech'), ('startup_building', 'Startup Building'), ('business_development', 'Business Development'), ('tech_in_nigeria', 'Breaking into Tech in Nigeria'), ('diaspora_pathways', 'Diaspora & International Opportunities'), ('postgrad_abroad', 'Postgraduate Studies Abroad'), ('nysc_guidance', 'NYSC & Early Career'), ('communication', 'Communication & Presentation'), ('leadership', 'Leadership & Teamwork'), ('open_source', 'Open Source Contribution'), ('other', 'Other')], max_length=50)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('work_mode', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')], default='Remote', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('available_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='core.alumniprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mentorships.mentorship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_applications', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorshipEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed'), ('terminated', 'Terminated'), ('archived', 'Archived')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_engagements', to='core.alumniprofile')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='mentorships.mentorship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_engagements', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mentorships.mentorship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_offers', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='core.alumniprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
