# Generated by Django 5.2.3 on 2026-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipengagement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('acknowledged', 'Acknowledged'), ('terminated', 'Terminated'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
