# Generated by Django 5.2.3 on 2026-05-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorshipapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipengagement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipoffer',
            unique_together=set(),
        ),
    ]
