# Generated by Django 5.2.3 on 2026-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0002_alter_mentorshipapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='category',
            field=models.CharField(choices=[('career_guidance', 'Career Guidance'), ('cv_and_portfolio', 'CV & Portfolio Building'), ('interview_prep', 'Interview Preparation'), ('linkedin_branding', 'LinkedIn & Personal Branding'), ('salary_negotiation', 'Salary Negotiation'), ('software_engineering', 'Software Engineering'), ('data_science', 'Data Science & Analytics'), ('product_management', 'Product Management'), ('product_design', 'Product Design & UX'), ('cybersecurity', 'Cybersecurity'), ('cloud_devops', 'Cloud & DevOps'), ('embedded_systems', 'Embedded Systems & IoT'), ('research_academia', 'Research & Academia'), ('entrepreneurship', 'Entrepreneurship'), ('freelancing', 'Freelancing & Remote Work'), ('fintech', 'Fintech'), ('agritech', 'Agritech'), ('startup_building', 'Startup Building'), ('business_development', 'Business Development'), ('tech_in_nigeria', 'Breaking into Tech in Nigeria'), ('diaspora_pathways', 'Diaspora & International Opportunities'), ('postgrad_abroad', 'Postgraduate Studies Abroad'), ('nysc_guidance', 'NYSC & Early Career'), ('communication', 'Communication & Presentation'), ('leadership', 'Leadership & Teamwork'), ('open_source', 'Open Source Contribution'), ('other', 'Other')], max_length=50),
        ),
    ]
