# Generated by Django 5.2.3 on 2026-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0002_alter_mentorshipengagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='category',
            field=models.CharField(choices=[('career_development', 'Career Development'), ('technical', 'Technical'), ('academic', 'Academic'), ('entrepreneurship', 'Entrepreneurship'), ('industry_specific', 'Industry Specific'), ('other', 'Other')], max_length=50),
        ),
    ]
