# Generated by Django 5.2.3 on 2026-08-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0003_alter_mentorship_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
    ]
