# Generated by Django 5.2.3 on 2026-08-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_studentresume_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement_type', models.CharField(choices=[('internship_engagement', 'Internship'), ('mentorship_engagement', 'Mentorship')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('acknowledged', 'Acknowledged'), ('terminated', 'Terminated'), ('archived', 'Archived')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.alumniprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
